"""empty message

Revision ID: cff2f1c5862e
Revises: b3a2ec25654a
Create Date: 2018-10-19 11:53:23.823827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cff2f1c5862e'
down_revision = 'b3a2ec25654a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goods',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('path', sa.String(length=100), nullable=True),
    sa.Column('price', sa.String(length=20), nullable=True),
    sa.Column('detail', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('goods')
    # ### end Alembic commands ###
